include(ExternalProject)

set(turfs_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/turfs)

set(turfs_CMAKE_ARGS
	-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
	-Wno-dev
)

if(ANDROID)
    set(turfs_CMAKE_ARGS "${turfs_CMAKE_ARGS} -DTURFS_TARGET_PLATFORM=TURFS_PLATFORM_ANDROID")
elseif(DREAMCAST)
    set(turfs_CMAKE_ARGS "${turfs_CMAKE_ARGS} -DTURFS_TARGET_PLATFORM=TURFS_PLATFORM_DREAMCAST")
elseif(IOS)
    set(turfs_CMAKE_ARGS "${turfs_CMAKE_ARGS} -DTURFS_TARGET_PLATFORM=TURFS_PLATFORM_IOS")
endif()

ExternalProject_Add(turfs_build
	PREFIX ${turfs_PREFIX}

	DOWNLOAD_DIR ${LUA_CONTRIB_DOWNLOAD_DIR}

	GIT_REPOSITORY git://github.com/eddieringle/turfs.git

	INSTALL_DIR ${LUA_TARGET_CONTRIB_OUT_DIR}
	CMAKE_ARGS ${turfs_CMAKE_ARGS}
)

add_library(turfs STATIC IMPORTED)
set_target_properties(turfs PROPERTIES
	IMPORTED_LOCATION ${LUA_TARGET_CONTRIB_OUT_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}turfs${CMAKE_STATIC_LIBRARY_SUFFIX}
)
add_dependencies(turfs turfs_build)
